### ISSUE TITLE
Problem: merchant's can't create pretty listings

### ISSUE THREAD

**Issue by gazhayes** [trofimarket/problems#20] opened 2021-06-26 05:30 UTC
Problem: merchant's can't create pretty listings

solution:
Implement https://github.com/nhn/tui.editor

1. Merchants upload (to IPFS) any images they want to use in the listing, IPFS links are displayed to the user.
2. Merchants create a Markdown file with text and using normal markdown linking to the images on IPFS.
3. On submit, the Markdown is uploaded to IPFS, the hash put into SC
4. When viewing the listing, Markdown file is fetched from IPFS and rendered on the listing page.

**Comment by samuelralak** [comment] 2021-07-12 14:36
Installed the toast ui editor and pushing the markdown content to ipfs, then storing hash in the smart contract.

Pending:

- [ ] Show markdown in auction item/listing page (please approve my new company so I can test this)
- [ ] Ui fixes (tools menu getting cut off in UI)

**Comment by ExcessionAtEsperi** [comment] 2021-07-12 16:02
Your PR broke the build:

```
npm ERR! code ENOLOCAL
npm ERR! Could not install from "node_modules/eth-sig-util/ethereumjs-abi@git+https:/github.com/ethereumjs/ethereumjs-abi.git" as it does not contain a package.json file.
```

and

```
> znft-client@0.1.0 build /home/trofi/znft-client
> craco build

(node:64650) UnhandledPromiseRejectionWarning: Error: craco: Config file not found. check if file exists at root (craco.config.js, .cracorc.js, .cracorc)
    at getConfigAsObject (/home/trofi/znft-client/node_modules/@craco/craco/lib/config.js:45:15)
    at loadCracoConfigAsync (/home/trofi/znft-client/node_modules/@craco/craco/lib/config.js:73:34)
    at Object.<anonymous> (/home/trofi/znft-client/node_modules/@craco/craco/scripts/build.js:21:1)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
(node:64650) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:64650) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by samuelralak** [comment] 2021-07-12 16:05
Its missing some config files. Pushing a fix in a few.

**Comment by samuelralak** [comment] 2021-07-12 16:14
@ExcessionAtEsperi [#9](https://github.com/trofimarket/znft-client/pull/9) should fix the second issue. Not entirely certain about the first one 🤔 but finding out

**Comment by ExcessionAtEsperi** [comment] 2021-07-13 02:43
@samuelralak FYI updating my local version of npm removes the first issue

**Comment by ExcessionAtEsperi** [comment] 2021-07-13 02:44
What version of npm are you running?

**Comment by ExcessionAtEsperi** [comment] 2021-07-13 02:55
@ssomraaj can you review and make sure that the markdown ipfs hash is going to the SC etc?

**Comment by samuelralak** [comment] 2021-07-13 03:01
@ExcessionAtEsperi I am using version `6.14.5` of npm.

The first issue was an unpredictable one, I suspect that it might have been caused by a package version mismatch. Deleting the old package-lock.json file might have fixed that but I updated package.json just to be safe.

The second one is a predictable one. It is caused by a missing configuration file specifically `craco.config.js` which is needed to make tailwind css work. I have included this file in the latest PR (which has since been merged).

**Comment by samuelralak** [comment] 2021-07-13 15:54
@gazhayes @ExcessionAtEsperi this should be completed by [#11](https://github.com/trofimarket/znft-client/pull/11), please validate. I have created a follow up issue here [#43](https://github.com/trofimarket/problems/issues/43) to fix the UI

**Closed** 2021-07-14 03:21 UTC
